NULL bytes in file
 Did once get this. Probably because file was not properly closed at power disconnect
   File "MT171.py", line 291, in <module>
     list = eval(line)
 TypeError: expected string without null bytes
So added a try exception around the eval